language: java

jdk:
  - openjdk7
#  - oraclejdk7
  - oraclejdk8

sudo: false

before_install:
  - pip install --user pylint
  - npm install --save-dev travis-after-all

script: set -e && make USE_CODECOV=1 all-but-emacs check

after_script:
  - |
      set +e
      declare exitCode;
      $(npm bin)/travis-after-all
      exitCode=$?

      if [ "$exitCode" -eq 0 ]; then
        if [[ ($TRAVIS_BRANCH == master) &&
              ($TRAVIS_PULL_REQUEST == false) ]] ; then
          curl -LO https://raw.github.com/mernst/plume-lib/master/bin/trigger-travis.sh
          sh trigger-travis.sh codespecs daikon $TRAVISTOKEN
          sh trigger-travis.sh typetests plume-lib-typecheck $TRAVISTOKEN
        fi
      fi

git:
  depth: 9
